/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ro.cti.ugal.proiect.java.vlad;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import ro.cti.ugal.proiect.java.GUIPrincipal;
import ro.cti.ugal.proiect.java.SursaIluminat;
import ro.cti.ugal.proiect.java.vlad.BecClasic;
import ro.cti.ugal.proiect.java.vlad.Material;

/**
 *
 * @author quadruple
 */
public class PanelBecClasic extends javax.swing.JPanel {
    private static Material[] materiale = {
        new Material("Tungsten", 5.6e-8, 0.0045),
        new Material("Grafit", 7.837e-6, -0.0005)
    };
    
    private static FileFilter filter = new FileNameExtensionFilter("Comma-separated values(.csv)", "csv");
    private static JFileChooser chooser = new JFileChooser();

    
    private static Material getMaterialForName(String nume) {
        for(Material m : materiale)
            if(m.nume.equalsIgnoreCase(nume))
                return m;
        
        // TODO: Daca nu a fost gasit nici un material cu acel nume, exceptie?
        return materiale[0];
    }
    
    private ArrayList<BecClasic> listaBecuri = new ArrayList<>();
    private void updateTabelFromLista() {
        DefaultTableModel model = (DefaultTableModel)tabelPrincipal.getModel();
        model.setRowCount(0);
        
        for(BecClasic c : listaBecuri)
            model.addRow(new Object[]{c.materialFilament.nume, 
                                      (double)c.lungimeFilament, 
                                      (double)c.diametruFilament, 
                                      (double)c.temperaturaCuloare, 
                                      (double)c.luminozitate
            });
    }
    
    /**
     * Creates new form PanelBecClasic
     */
    public PanelBecClasic() {
        initComponents();
        
        chooser.setFileFilter(filter);
        
        VladTest.main(new String[]{});
        
        for(BecClasic i : VladTest.listaBecuriClasic)
            listaBecuri.add(i);
        
        updateTabelFromLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxMaterial = new javax.swing.JComboBox<>();
        labelTipMaterial = new javax.swing.JLabel();
        textfieldLungimeFilament = new javax.swing.JTextField();
        labelLungimeFilament = new javax.swing.JLabel();
        textfieldDiametruFilament = new javax.swing.JTextField();
        labelDiametruFilament = new javax.swing.JLabel();
        labelTempOp = new javax.swing.JLabel();
        textfieldTempOp = new javax.swing.JTextField();
        labelEficientaLuminoasa = new javax.swing.JLabel();
        textfieldEficientaLuminoasa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPrincipal = new javax.swing.JTable();
        butonAdaugare = new javax.swing.JButton();
        butonStergere = new javax.swing.JButton();
        labelFiltru1 = new javax.swing.JLabel();
        comboBoxFiltruTermen1 = new javax.swing.JComboBox<>();
        comboBoxFiltruConditie = new javax.swing.JComboBox<>();
        textfieldFiltruTermen2 = new javax.swing.JTextField();
        butonFiltrare = new javax.swing.JButton();
        butonOpen = new javax.swing.JButton();
        butonSave = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        comboBoxMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tungsten", "Grafit" }));
        comboBoxMaterial.setName(""); // NOI18N

        labelTipMaterial.setText("Material");

        textfieldLungimeFilament.setText("0.5");

        labelLungimeFilament.setText("Lungime Filament");

        textfieldDiametruFilament.setText("4.6e-5");

        labelDiametruFilament.setText("Diametru filament");

        labelTempOp.setText("Temp. Operationala");

        textfieldTempOp.setText("3200");

        labelEficientaLuminoasa.setText("Eficienta Luminoasa");

        textfieldEficientaLuminoasa.setText("15");

        tabelPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Lungime Filament", "Diametru Filament", "Temperatura Culoare", "Luminozitate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelPrincipal);

        butonAdaugare.setText("Adauga");
        butonAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAdaugareActionPerformed(evt);
            }
        });

        butonStergere.setText("Sterge");
        butonStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonStergereActionPerformed(evt);
            }
        });

        labelFiltru1.setText("Filtrul");

        comboBoxFiltruTermen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lungime Filament", "Diametru Filament", "Temperatura Culoare", "Luminozitate" }));

        comboBoxFiltruConditie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Egal", "Mai mare", "Mai mic" }));

        textfieldFiltruTermen2.setText("0.5");

        butonFiltrare.setText("Filtreaza");
        butonFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonFiltrareActionPerformed(evt);
            }
        });

        butonOpen.setText("Open");
        butonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOpenActionPerformed(evt);
            }
        });

        butonSave.setText("Save");
        butonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textfieldEficientaLuminoasa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelEficientaLuminoasa))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboBoxMaterial, 0, 117, Short.MAX_VALUE)
                                .addComponent(textfieldDiametruFilament)
                                .addComponent(textfieldLungimeFilament))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelDiametruFilament)
                                .addComponent(labelLungimeFilament)
                                .addComponent(labelTipMaterial)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textfieldTempOp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelTempOp)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butonAdaugare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonStergere, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFiltru1)
                    .addComponent(comboBoxFiltruTermen1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxFiltruConditie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldFiltruTermen2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(butonOpen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butonSave))
                        .addComponent(butonFiltrare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxMaterial)
                            .addComponent(labelTipMaterial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldLungimeFilament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLungimeFilament))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldDiametruFilament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDiametruFilament))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTempOp)
                            .addComponent(textfieldTempOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldEficientaLuminoasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEficientaLuminoasa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butonAdaugare)
                            .addComponent(butonStergere))
                        .addGap(43, 43, 43)
                        .addComponent(labelFiltru1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxFiltruTermen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxFiltruConditie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldFiltruTermen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonFiltrare)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butonOpen)
                            .addComponent(butonSave))
                        .addGap(314, 314, 314))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butonAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAdaugareActionPerformed
        // TODO add your handling code here:

        Material material = getMaterialForName((String)comboBoxMaterial.getSelectedItem());
        double lungimeFilament = Double.parseDouble(textfieldLungimeFilament.getText());
        double diametruFilament = Double.parseDouble(textfieldDiametruFilament.getText());
        double temperaturaOperationala = Double.parseDouble(textfieldTempOp.getText());
        double eficientaLuminoasa = Double.parseDouble(textfieldEficientaLuminoasa.getText());
        
        listaBecuri.add(new BecClasic(material, lungimeFilament, diametruFilament, temperaturaOperationala, eficientaLuminoasa));
        updateTabelFromLista();
    }//GEN-LAST:event_butonAdaugareActionPerformed

    private void butonStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonStergereActionPerformed
        // TODO add your handling code here:
        listaBecuri.remove(tabelPrincipal.getSelectedRow());
        updateTabelFromLista(); 
    }//GEN-LAST:event_butonStergereActionPerformed

    private void butonFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonFiltrareActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabelPrincipal.getModel();

        int filtruTermen1 = comboBoxFiltruTermen1.getSelectedIndex();
        String filtruConditie = (String)comboBoxFiltruConditie.getSelectedItem();
        String filtruTermen2 = textfieldFiltruTermen2.getText();
        
        double termen2 = Double.parseDouble(filtruTermen2);
        for(int i = model.getRowCount() - 1; i >= 0; i--) {
            System.out.println(i);
            System.out.println(model.getValueAt(i, filtruTermen1 + 1).getClass().getSimpleName());
            Double termen1 = (double) model.getValueAt(i, filtruTermen1 + 1);
            
            switch(filtruConditie) {
                default: 
                case "Egal": {
                    if(termen1 != termen2)
                        listaBecuri.remove(i);
                    break;
                }
                
                case "Mai mare": {
                    if(termen1 < termen2)
                        listaBecuri.remove(i);
                    break;
                }
                
                case "Mai mic": {
                    if(termen1 > termen2)
                        listaBecuri.remove(i);
                    break;
                }
            }
        }
        
        updateTabelFromLista();
    }//GEN-LAST:event_butonFiltrareActionPerformed

    private void butonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOpenActionPerformed
        // TODO add your handling code here:
        chooser.showOpenDialog(this);
        
        try {
            FileReader file = new FileReader(chooser.getSelectedFile().getPath());
            BufferedReader reader = new BufferedReader(file);
            reader.readLine(); // Citiim prima linie, este header-ul.
            
            // Daca am ajuns aici, fisierul poate fii citit. Putem sa dam clear
            // la lista de becuri.
            listaBecuri.clear();
            
            String currentLine = reader.readLine();
            while(currentLine != null) {
                String[] parametrii = currentLine.split(",");
                
                Material material = getMaterialForName(parametrii[0]);
                BecClasic c = new BecClasic();
                c.materialFilament = material;
                c.lungimeFilament = Double.parseDouble(parametrii[1]);
                c.diametruFilament = Double.parseDouble(parametrii[2]);
                c.luminozitate = Integer.parseInt(parametrii[3]);
                c.temperaturaCuloare = Integer.parseInt(parametrii[4]);
                c.consum = (short)Integer.parseInt(parametrii[5]);
                c.indiceRedareCuloare = (float)Float.parseFloat(parametrii[6]);
                
                listaBecuri.add(c);
                
                currentLine = reader.readLine();
            }
        } catch (IOException ex) {
            System.out.println("Exception occured: " + ex.toString());
        }
        
        updateTabelFromLista();
    }//GEN-LAST:event_butonOpenActionPerformed

    private void butonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSaveActionPerformed
        // TODO add your handling code here:
        chooser.showSaveDialog(this);
        
        try {
            FileWriter file = new FileWriter(chooser.getSelectedFile().getPath());
            file.write("Material,Lungime filament,Diametru filament,Luminozitate,Temperatura culoare,Consum,Indice redare culoare\n");
            for(BecClasic c : this.listaBecuri) {
                file.write("%s,%f,%f,%d,%d,%d,%f\n".formatted(
                        c.materialFilament.nume,
                        c.lungimeFilament,
                        c.diametruFilament,
                        c.luminozitate,
                        c.temperaturaCuloare,
                        c.consum,
                        c.indiceRedareCuloare
                ));
            }
            file.close();
        } catch (IOException ex) {
            System.out.println("Exception occured: " + ex.toString());
        }
    }//GEN-LAST:event_butonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAdaugare;
    private javax.swing.JButton butonFiltrare;
    private javax.swing.JButton butonOpen;
    private javax.swing.JButton butonSave;
    private javax.swing.JButton butonStergere;
    private javax.swing.JComboBox<String> comboBoxFiltruConditie;
    private javax.swing.JComboBox<String> comboBoxFiltruTermen1;
    private javax.swing.JComboBox<String> comboBoxMaterial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDiametruFilament;
    private javax.swing.JLabel labelEficientaLuminoasa;
    private javax.swing.JLabel labelFiltru1;
    private javax.swing.JLabel labelLungimeFilament;
    private javax.swing.JLabel labelTempOp;
    private javax.swing.JLabel labelTipMaterial;
    private javax.swing.JTable tabelPrincipal;
    private javax.swing.JTextField textfieldDiametruFilament;
    private javax.swing.JTextField textfieldEficientaLuminoasa;
    private javax.swing.JTextField textfieldFiltruTermen2;
    private javax.swing.JTextField textfieldLungimeFilament;
    private javax.swing.JTextField textfieldTempOp;
    // End of variables declaration//GEN-END:variables
}
